// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyzcwcdqntxudqjftzsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5emN3Y2RxbnR4dWRxamZ0enN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2ODAxNjAsImV4cCI6MjA3NzI1NjE2MH0.znJlYZuSRCDrw7xQBW9zWzC9AZbo7NPJHtQW9jTDGPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});